version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: szandany/liquibase
    steps:
      - run: |
          echo "Hi I'm on Runners!"
          whoami
          ls
          pwd