# This is a basic workflow to help you get started with Actions

name: Liquibase_CLI_GitHub-Hosted

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
    user.email: "<email>"
    user.name: "<username>"
    message: "<enter commit message>"
    branch: "<git branch name>"
    LB_VERSION: "4.6.1"

jobs:

  Build_Job:
    runs-on: ubuntu-latest
    environment: 
      name: DEV

    steps:
      - name: Build with Liquibase
        uses: actions/checkout@v2
      - run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v${LB_VERSION}/liquibase-${LB_VERSION}.zip --output liquibase-${LB_VERSION}.zip
          unzip -o -d liquibase liquibase-${LB_VERSION}.zip
          export LIQUIBASE_PRO_LICENSE_KEY="${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_URL }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_USERNAME }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}"
          ./liquibase/liquibase --version
    
  Test_Job:
    runs-on: ubuntu-latest
    environment: 
      name: TEST

    steps:
      - name: Test with Liquibase
        uses: actions/checkout@v2
      - run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v${LB_VERSION}/liquibase-${LB_VERSION}.zip --output liquibase-${LB_VERSION}.zip
          unzip -o -d liquibase liquibase-${LB_VERSION}.zip
          export LIQUIBASE_PRO_LICENSE_KEY="${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_URL }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_USERNAME }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}"
          echo "${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}"
          ./liquibase/liquibase --version
