# This is a basic workflow to help you get started with Actions

name: Liquibase_CLI_GitHub-Hosted

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
   inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'severe'
      
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  LBJobCLI:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    environment: 
      name: DEV
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: RunLiquibaseCLICommands
        uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell

      - run: |
          $Env:LIQUIBASE_PRO_LICENSE_KEY="${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}"
          $Env:LIQUIBASE_COMMAND_URL="${{ secrets.LIQUIBASE_COMMAND_URL }}"
          $Env:LIQUIBASE_COMMAND_USERNAME="${{ secrets.LIQUIBASE_COMMAND_USERNAME }}"
          $Env:LIQUIBASE_COMMAND_PASSWORD="${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}"
          $Env:LIQUIBASE_COMMAND_CHANGELOG_FILE="${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}"
          $Env:LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_SETTINGS_FILE="${{ secrets.LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_SETTINGS_FILE }}"
          $Env:Path += ";C:\apps\liquibase"
          
          
          liquibase --version
          liquibase --changelog-file=changelog.sql status --verbose
